name: Release Plugin version to Moodle Marketplace

on:
  push:
    tags:
      - 'v*' # only syncgit2 adds v* tags when pushing.
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released (e.g. v1.4.0)'
        required: true
  workflow_run:
     workflows: ["Moodle Plugin CI"]
     types:
       - completed

jobs:
  release-to-marketplace:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: moodlehq/moodle-plugin-release/.github/workflows/moodle-release.yml@main
    with:
      tag: ${{ inputs.tag }}
    secrets:
      MOODLE_MARKETPLACE_TOKEN: ${{ secrets.MOODLE_MARKETPLACE_TOKEN }}
